[idris2]
version = "0.5.1"
commit  = "7a5f63eab089b98a1cca75eb0719ed7814499fa8"

[db.bytestring]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "e06ca875ce5eba11bc3faa62f18ba652c0ea73a1"
ipkg   = "bytestring.ipkg"

[db.collie]
type   = "github"
url    = "https://github.com/ohad/collie"
commit = "46bff04a8d9a1598fec9b19f515541df16dc64ef"
ipkg   = "collie.ipkg"

[db.comonad]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-comonad"
commit = "4bfe255605a3e6604dc04d6e928a73be62160256"
ipkg   = "comonad.ipkg"

[db.dinwiddy]
type   = "github"
url    = "https://github.com/bobbbay/dinwiddy"
commit = "4302331294e6e2b4fb1ee46ccd782e78070e4911"
ipkg   = "dinwiddy.ipkg"

[db.dom]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-dom"
commit = "4685375ce855a17ba35bd7b0e02d88e4c5058a0e"
ipkg   = "dom.ipkg"

[db.eff]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-eff"
commit = "22f62ed3e5b2bae06d02e7a8b4e06f785d242718"
ipkg   = "eff.ipkg"

[db.elab-util]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "29f8153c0c06a69a168f009823a31bae266c5306"
ipkg   = "elab-util.ipkg"

[db.freer]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-freer"
commit = "ed81c9faf514bc4bd5c7fdd383d6199ac6dd22b5"
ipkg   = "freer.ipkg"

[db.fvect]
type   = "github"
url    = "https://github.com/mattpolzin/idris-fvect"
commit = "d84969fce38ff8a10b9d261458f4d495e6e0f1ca"
ipkg   = "fvect.ipkg"

[db.hashable]
type   = "github"
url    = "https://github.com/Z-snails/Idris2-hashable"
commit = "d97d2c39d9199941e2de1991224f564fc4b956dd"
ipkg   = "hashable.ipkg"

[db.hedgehog]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-hedgehog"
commit = "e9858609ea79f0d2e36e66bfb9a2dbceba7771cc"
ipkg   = "hedgehog.ipkg"

[db.idrall]
type   = "github"
url    = "https://github.com/alexhumphreys/idrall"
commit = "b5f04575c94cc5cc006791d81f106f5492e3b8f3"
ipkg   = "idrall.ipkg"

[db.indexed]
type   = "github"
url    = "https://github.com/mattpolzin/idris-indexed"
commit = "21e448e4da193425336ae150bc55e015c6445415"
ipkg   = "indexed.ipkg"

[db.json]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-json"
commit = "2d0931546afd1152a55da9e6bf50d0fd8dd99dee"
ipkg   = "json.ipkg"

[db.katla]
type   = "github"
url    = "https://github.com/idris-community/katla"
commit = "e16c1ec10e9be17cba6f70e91aa3983fa85d521c"
ipkg   = "katla.ipkg"

[db.lsp]
type   = "github"
url    = "https://github.com/idris-community/idris2-lsp"
commit = "e9139f34a74ac5e364804b539d02a451b014ea57"
ipkg   = "lsp.ipkg"

[db.pack]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pack"
commit = "1e3f2016777775bcdb1cb2ffbea28fcd06f4e56a"
ipkg   = "pack.ipkg"

[db.pg-idris]
type   = "github"
url    = "https://github.com/mattpolzin/pg-idris"
commit = "6f7b2f6c96f963e5073c39613ccd394bc2f3ace5"
ipkg   = "pg-idris.ipkg"

[db.prettier]
type   = "github"
url    = "https://github.com/Z-snails/prettier"
commit = "0222ada0be5f6abf5528c8513181f2f4ad117b4b"
ipkg   = "prettier.ipkg"

[db.pretty-show]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pretty-show"
commit = "d31e1f5a191a78deea1170beee21401da063ed8d"
ipkg   = "pretty-show.ipkg"

[db.prim]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-prim"
commit = "457fcd05a093d509841d624b83f4fccb54a9c6a4"
ipkg   = "prim.ipkg"

[db.rhone]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-rhone"
commit = "33441db6a0a26bb04ff16b72c0224eaa04b5fee8"
ipkg   = "rhone.ipkg"

[db.rhone-js]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-rhone-js"
commit = "b5cfde2b35e483d1231619a741cfce8b3a8ea438"
ipkg   = "rhone-js.ipkg"

[db.snocvect]
type   = "github"
url    = "https://github.com/mattpolzin/idris-snocvect"
commit = "f6148c3d06c7a9989062a2425f925fc844468215"
ipkg   = "snocvect.ipkg"

[db.sop]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-sop"
commit = "af9224510f5c283f3b3c8293524e51c225617658"
ipkg   = "sop.ipkg"

[db.tailrec]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-tailrec"
commit = "dd0bc6381b3a2e69aa37f9a8c1b165d4b1516ad7"
ipkg   = "tailrec.ipkg"

[db.tester]
type   = "github"
url    = "https://github.com/cuddlefishie/tester-idr"
commit = "3dcdb54ed578a14597a17cb93c926734a9da69ca"
ipkg   = "tester.ipkg"

[db.toml]
type   = "github"
url    = "https://github.com/cuddlefishie/toml-idr"
commit = "b4f5a4bd874fa32f20d02311a62a1910dc48123f"
ipkg   = "toml.ipkg"

[db.xml]
type   = "github"
url    = "https://github.com/madman-bob/idris2-xml"
commit = "1292ccfcd58c551089ef699e4560343d5c473d64"
ipkg   = "xml.ipkg"
