[idris2]
url     = "https://github.com/idris-lang/Idris2"
version = "0.6.0"
commit  = "b03ce53e9755ef23137c7e805ee70c643560a670"

[db.algebra]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-algebra"
commit      = "e1bf005cc30978d84b0c48fd7a267d7a9bcf23a7"
ipkg        = "algebra.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.ansi]
type        = "github"
url         = "https://github.com/idris-community/idris2-ansi"
commit      = "f3cac49b50561c0182ce2d7d9bdc4de8000f5a3e"
ipkg        = "ansi.ipkg"
packagePath = false

[db.apache-mime-types]
type        = "github"
url         = "https://github.com/kbertalan/idris2-apache-mime-types"
commit      = "973de0e7224a25606eca25a1caf853b83925d36d"
ipkg        = "apache-mime-types.ipkg"
packagePath = false

[db.barbies]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-barbies"
commit      = "24bd6d2fcc257d7dcdbe2a4fb992604bb5ab21c9"
ipkg        = "barbies.ipkg"
packagePath = false

[db.bounded-doubles]
type        = "github"
url         = "https://github.com/buzden/idris2-bounded-doubles"
commit      = "54162ac158fc2ddf89f70b7069c2930f503530a2"
ipkg        = "bounded-doubles.ipkg"
packagePath = false
test        = "tests/library-tests.ipkg"

[db.bounded-doubles-hedgehog-generators]
type        = "github"
url         = "https://github.com/buzden/idris2-bounded-doubles"
commit      = "54162ac158fc2ddf89f70b7069c2930f503530a2"
ipkg        = "hedgehog-generators.ipkg"
packagePath = false
test        = "tests/generators-tests.ipkg"

[db.bytestring]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-bytestring"
commit      = "950b47248f3e31d713bdb75c1a13a1d0da846666"
ipkg        = "bytestring.ipkg"
packagePath = false

[db.cheerio]
type        = "github"
url         = "https://github.com/running-grass/idris2-playground"
commit      = "0dacfd81b49749d68a5fd905e95c860fdab072ab"
ipkg        = "cheerio/cheerio.ipkg"
packagePath = false

[db.collie]
type        = "github"
url         = "https://github.com/ohad/collie"
commit      = "46bff04a8d9a1598fec9b19f515541df16dc64ef"
ipkg        = "collie.ipkg"
packagePath = false

[db.comonad]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-comonad"
commit      = "38f4b26f6a7b58f173ab1924486e887d40042ddd"
ipkg        = "comonad.ipkg"
packagePath = false

[db.coop]
type        = "github"
url         = "https://github.com/buzden/idris2-coop"
commit      = "eec20769190da350e32288db59972261881ecdd5"
ipkg        = "coop.ipkg"
packagePath = false
test        = "tests/tests.ipkg"

[db.crypt]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-crypt"
commit      = "84e2c1a594fe7323440b79bb5782053a176b45be"
ipkg        = "crypt.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.dinwiddy]
type        = "github"
url         = "https://github.com/bobbbay/dinwiddy"
commit      = "61a81c55e48e4b7b551fb7493d623cb7659a37ce"
ipkg        = "dinwiddy.ipkg"
packagePath = false

[db.distribution]
type        = "github"
url         = "https://github.com/idris-bayes/distribution"
commit      = "bced45ab5367184c8a4d88ce695c9a4714c34c98"
ipkg        = "distribution.ipkg"
packagePath = false

[db.dom]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-dom"
commit      = "cc84287d71bda1d9c9523b455f20fd03d1b0598e"
ipkg        = "dom.ipkg"
packagePath = false

[db.eff]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-eff"
commit      = "51a0bf19d7eeebda3706d8562d32127bf8108559"
ipkg        = "eff.ipkg"
packagePath = false

[db.effect]
type        = "github"
url         = "https://github.com/Russoul/Idris2-Effect"
commit      = "b76dce14b79a5f743243a294c3474c6f113f8e3a"
ipkg        = "effect.ipkg"
packagePath = false

[db.elab-pretty]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-elab-util"
commit      = "c9430a87c397287810fc1297ae64444773afa537"
ipkg        = "elab-pretty.ipkg"
packagePath = false

[db.elab-util]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-elab-util"
commit      = "c9430a87c397287810fc1297ae64444773afa537"
ipkg        = "elab-util.ipkg"
packagePath = false

[db.filepath]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-filepath"
commit      = "4f25bf8009cd826d08a55e0e021de83099e107f0"
ipkg        = "filepath.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.fix-whitespace]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris-fix-whitespace"
commit      = "9e719d201ceea41cc953e803bbf848f8ed03e2fe"
ipkg        = "fix-whitespace.ipkg"
packagePath = false

[db.free]
type        = "github"
url         = "https://github.com/idris-bayes/free"
commit      = "809e1450094eab85a64f926967f8b056402291d6"
ipkg        = "free.ipkg"
packagePath = false

[db.freer]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-freer"
commit      = "481c19535a020166d9babd5f5156161e4dbce4ba"
ipkg        = "freer.ipkg"
packagePath = false

[db.fvect]
type        = "github"
url         = "https://github.com/mattpolzin/idris-fvect"
commit      = "d84969fce38ff8a10b9d261458f4d495e6e0f1ca"
ipkg        = "fvect.ipkg"
packagePath = false

[db.game-2048]
type        = "github"
url         = "https://github.com/running-grass/idris2-playground"
commit      = "0dacfd81b49749d68a5fd905e95c860fdab072ab"
ipkg        = "game-2048/game-2048.ipkg"
packagePath = false

[db.getopts]
type        = "github"
url         = "https://github.com/idris-community/idris2-getopts"
commit      = "9fccb8f31c0ae18f4e07c81f110192a0e2b6e0bb"
ipkg        = "getopts.ipkg"
packagePath = false

[db.golden-runner-helper]
type        = "github"
url         = "https://github.com/buzden/idris2-golden-runner-helper"
commit      = "e1c056e212a4f0e22b37c65177c2586b9efed67e"
ipkg        = "golden-runner-helper.ipkg"
packagePath = false
test        = "tests/tests.ipkg"

[db.graph]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-graph"
commit      = "3beaa460ea9b91a40c9581770321a6915fd74d20"
ipkg        = "graph.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.hashable]
type        = "github"
url         = "https://github.com/Z-snails/Idris2-hashable"
commit      = "5615bd4627fedcb6122e902ea3d4d18575459ceb"
ipkg        = "hashable.ipkg"
packagePath = false

[db.hashmap]
type        = "github"
url         = "https://github.com/Z-snails/idris2-hashmap"
commit      = "58f5a2d2c0a7bb082666d6ce668ee242185a52bf"
ipkg        = "hashmap.ipkg"
packagePath = false

[db.hedgehog]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-hedgehog"
commit      = "8fc72f2aa95802a936fc0d10fd9f4dfa4b78b886"
ipkg        = "hedgehog.ipkg"
packagePath = false

[db.idrall]
type        = "github"
url         = "https://github.com/alexhumphreys/idrall"
commit      = "62a455894b1db5134c8b56d31aadb31d483a4b2c"
ipkg        = "idrall.ipkg"
packagePath = false

[db.idrisGL]
type        = "github"
url         = "https://github.com/ECburx/Idris2GL"
commit      = "3ed89f3116569260d766d14908cba9debbcea9ff"
ipkg        = "idrisGL.ipkg"
packagePath = false

[db.if-unsolved-implicit]
type        = "github"
url         = "https://github.com/buzden/idris2-if-unsolved-implicit"
commit      = "ca68ca72da60f538beb315c424091f4708a114c5"
ipkg        = "if-unsolved-implicit.ipkg"
packagePath = false
test        = "tests/tests.ipkg"

[db.indexed]
type        = "github"
url         = "https://github.com/mattpolzin/idris-indexed"
commit      = "6a10e418ef2dcdef66f8de7ee9e29edd1aa7c179"
ipkg        = "indexed.ipkg"
packagePath = false

[db.js]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-dom"
commit      = "cc84287d71bda1d9c9523b455f20fd03d1b0598e"
ipkg        = "js/js.ipkg"
packagePath = false

[db.json]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-json"
commit      = "0f87c80f353b6c4094f720154ec6792273755c0a"
ipkg        = "json.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.katla]
type        = "github"
url         = "https://github.com/idris-community/katla"
commit      = "685bb35aac5302bc3b3f91500b7b276c98877bc4"
ipkg        = "katla.ipkg"
packagePath = false

[db.log-domain]
type        = "github"
url         = "https://github.com/idris-bayes/log-domain"
commit      = "7eb33c36fb411b3e9dc43e0c5ad5d8f2f3dae80e"
ipkg        = "log-domain.ipkg"
packagePath = false

[db.lsp]
type        = "github"
url         = "https://github.com/idris-community/idris2-lsp"
commit      = "84966edb579c73416545e35f68dccaad9e0388b4"
ipkg        = "lsp.ipkg"
packagePath = true

[db.markdown]
type        = "github"
url         = "https://github.com/running-grass/idris2-markdown"
commit      = "38334267cbbe0ed067320d2e8bec36b08f475f5a"
ipkg        = "markdown.ipkg"
packagePath = false

[db.matrix]
type        = "github"
url         = "https://github.com/running-grass/idris2-playground"
commit      = "0dacfd81b49749d68a5fd905e95c860fdab072ab"
ipkg        = "matrix/matrix.ipkg"
packagePath = false

[db.mtl-tuple-impls]
type        = "github"
url         = "https://github.com/buzden/idris2-mtl-tuple-impls"
commit      = "101fa0ccbd0fbfbe4807a6eb871b639740cbe6e8"
ipkg        = "mtl-tuple-impls.ipkg"
packagePath = false
test        = "tests/tests.ipkg"

[db.multiplate]
type        = "github"
url         = "https://github.com/Z-snails/multiplate-idr"
commit      = "601d865f1fc74b783879b50d17ffd2a949def902"
ipkg        = "multiplate.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.ncurses-idris]
type        = "github"
url         = "https://github.com/mattpolzin/ncurses-idris"
commit      = "58787352ce275e0c1da66b1ea54fd71762ee8f82"
ipkg        = "ncurses-idris.ipkg"
packagePath = false

[db.node]
type        = "github"
url         = "https://github.com/kbertalan/idris2-node"
commit      = "917e6cb32b1ba6e171170b4d713acaff1fea79d6"
ipkg        = "node.ipkg"
packagePath = false

[db.pack]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-pack"
commit      = "00606a3c13e44abcec71627271bbb6751d76cf8a"
ipkg        = "pack.ipkg"
packagePath = false

[db.pack-admin]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-pack"
commit      = "00606a3c13e44abcec71627271bbb6751d76cf8a"
ipkg        = "pack-admin.ipkg"
packagePath = false

[db.park_bench]
type        = "github"
url         = "https://github.com/Z-snails/park_bench"
commit      = "c9a212e4873cc533dee361e1614189c95a56c873"
ipkg        = "park_bench.ipkg"
packagePath = false

[db.parser]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-parser"
commit      = "a7c05db58b3070bfa7b25ab0ef2b7c53294ba50a"
ipkg        = "parser.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.pg-idris]
type        = "github"
url         = "https://github.com/mattpolzin/pg-idris"
commit      = "75b931004f98043125754dfc84361c1fef2cf4b7"
ipkg        = "pg-idris.ipkg"
packagePath = false

[db.prettier]
type        = "github"
url         = "https://github.com/Z-snails/prettier"
commit      = "fb572512d7f14a72868cdfa1f8cb2f2aaba2a716"
ipkg        = "prettier.ipkg"
packagePath = false

[db.prettier-ansi]
type        = "github"
url         = "https://github.com/idris-community/idris2-ansi"
commit      = "f3cac49b50561c0182ce2d7d9bdc4de8000f5a3e"
ipkg        = "prettier/prettier-ansi.ipkg"
packagePath = false

[db.pretty-show]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-pretty-show"
commit      = "3ed70e7bfe5c56819cfd5895fe8f62409f4b07ab"
ipkg        = "pretty-show.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.prim]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-prim"
commit      = "8080c4b9c7a326fcb0ebef8d0b2bf77329c5be48"
ipkg        = "prim.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.profiler]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-profiler"
commit      = "a6d5be5a752911d72b52323e4553285fb6b6cb86"
ipkg        = "profiler.ipkg"
packagePath = false

[db.promise]
type        = "github"
url         = "https://github.com/kbertalan/idris2-promise"
commit      = "0b1716525ee10ed3a4f0d7132107c83e88f8eb99"
ipkg        = "promise.ipkg"
packagePath = false

[db.random-pure]
type        = "github"
url         = "https://github.com/buzden/idris2-random-pure"
commit      = "c7e2c1388e1f61ace08f1e117f50a60731f1442a"
ipkg        = "random-pure.ipkg"
packagePath = false
test        = "tests/tests.ipkg"

[db.refined]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-refined"
commit      = "9e6255b3bbf0e53645a5bac7d81c72efc7cb132b"
ipkg        = "refined.ipkg"
packagePath = false

[db.rhone]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-rhone"
commit      = "e05bff75952ee9bdf43f0c09a20886d344d04ca6"
ipkg        = "rhone.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.rhone-js]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-rhone-js"
commit      = "fb0122a3fcc89218913892cbe8352d5b8428d1d0"
ipkg        = "rhone-js.ipkg"
packagePath = false

[db.rio]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-rio"
commit      = "b8d7adcccd96f3b0bce7ec6843d7cff5d5556a76"
ipkg        = "rio.ipkg"
packagePath = false
test        = "test.ipkg"

[db.snocvect]
type        = "github"
url         = "https://github.com/mattpolzin/idris-snocvect"
commit      = "f6148c3d06c7a9989062a2425f925fc844468215"
ipkg        = "snocvect.ipkg"
packagePath = false

[db.sop]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-sop"
commit      = "0726a1154b55ba0cefb885962a726c847b3d8d43"
ipkg        = "sop.ipkg"
packagePath = false

[db.string-builder]
type        = "github"
url         = "https://github.com/Z-snails/string-builder"
commit      = "6dfb5e0070274ead1b8fd4e1229b5254da7ddd15"
ipkg        = "string-builder.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.summary-stat]
type        = "github"
url         = "https://github.com/buzden/idris2-summary-stat"
commit      = "412269d6e0d1c23419ee65923276363e94fd5ded"
ipkg        = "summary-stat.ipkg"
packagePath = false
test        = "tests/tests.ipkg"

[db.tailrec]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-tailrec"
commit      = "d3747284c7e80a711464ec4b1a7976bcf39dd6f2"
ipkg        = "tailrec.ipkg"
packagePath = false

[db.tester]
type        = "github"
url         = "https://github.com/cuddlefishie/tester-idr"
commit      = "3dcdb54ed578a14597a17cb93c926734a9da69ca"
ipkg        = "tester.ipkg"
packagePath = false

[db.time-for-sleep]
type        = "github"
url         = "https://github.com/buzden/idris2-time-for-sleep"
commit      = "9b4bcd543c41f0d0bb6fda3e16c403e2c0708387"
ipkg        = "time-for-sleep.ipkg"
packagePath = false
test        = "tests/tests.ipkg"

[db.timeit]
type        = "github"
url         = "https://github.com/MarcelineVQ/idris2-timeit"
commit      = "9566f71e9e7a68e8da4a30b8318f40099dda5c11"
ipkg        = "timeit.ipkg"
packagePath = false

[db.tls]
type        = "github"
url         = "https://github.com/octeep/idris2-tls"
commit      = "fd03fa32e1ea05b97466ba57b9c1f641550d9557"
ipkg        = "tls.ipkg"
packagePath = false

[db.toml]
type        = "github"
url         = "https://github.com/cuddlefishie/toml-idr"
commit      = "b4f5a4bd874fa32f20d02311a62a1910dc48123f"
ipkg        = "toml.ipkg"
packagePath = false

[db.typelevel-emptiness-collections]
type        = "github"
url         = "https://github.com/buzden/idris2-typelevel-emptiness-collections"
commit      = "6bf625d144477973fdfacf838524bb90a04e87f2"
ipkg        = "typelevel-emptiness-collections.ipkg"
packagePath = false
test        = "tests/tests.ipkg"

[db.tyre]
type        = "github"
url         = "https://github.com/kasiaMarek/TyRE"
commit      = "6e40ff94a514e21f787fa19c23573ea2ff9ffbb9"
ipkg        = "tyre.ipkg"
packagePath = false

[db.tyttp]
type        = "github"
url         = "https://github.com/kbertalan/tyttp"
commit      = "0dd24444d8980cb0d1b4faf9b8dd505e77468ba9"
ipkg        = "tyttp.ipkg"
packagePath = false

[db.tyttp-json]
type        = "github"
url         = "https://github.com/kbertalan/tyttp-json"
commit      = "ecaf5306c8ec4186e932249435f48e16b0a75729"
ipkg        = "tyttp-json.ipkg"
packagePath = false

[db.uniplate]
type        = "github"
url         = "https://github.com/Z-snails/uniplate-idr"
commit      = "caac354759a62a52596b6f77971327e17ff81c0f"
ipkg        = "uniplate.ipkg"
packagePath = false

[db.url]
type        = "github"
url         = "https://github.com/running-grass/idris2-url"
commit      = "4587b14fbe7752c4aad5aac045e19088ec2e4108"
ipkg        = "url.ipkg"
packagePath = false

[db.webidl]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-webidl"
commit      = "d380dcbf1b30466e888c0028ac3fecb775ef037f"
ipkg        = "webidl.ipkg"
packagePath = false
test        = "test/test.ipkg"

[db.xml]
type        = "github"
url         = "https://github.com/madman-bob/idris2-xml"
commit      = "1292ccfcd58c551089ef699e4560343d5c473d64"
ipkg        = "xml.ipkg"
packagePath = false
