[idris2]
version = "0.8.0"
url     = "https://github.com/idris-lang/Idris2"
commit  = "main"

[db.enum]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-enum"
commit = "main"
ipkg   = "enum.ipkg"

[db.finite]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-finite"
commit = "main"
ipkg   = "finite.ipkg"
test   = "test/test.ipkg"

[db.pack]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pack"
commit = "main"
ipkg   = "pack.ipkg"

[db.async-kqueue]
type   = "github"
url    = "https://github.com/Matthew-Mosior/idris2-async-kqueue"
commit = "main"
ipkg   = "async-kqueue.ipkg"
